version: "3.4"

services:
  workspace:
    build:
      context: containers/workspace
      args:
        - NODE_VERSION=${NODE_VERSION}
        - WORKING_DIR=${APP_CODE_PATH_CONTAINER}
    ports:
      - "4200:4200"
      - "4201:4201"
      - "9876:9876"
    tty: true
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}

  nginx:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    ports:
      - "80:80"
