version: "3.4"

networks:
  terrasse:
    driver: ${NETWORKS_DRIVER}

services:
  workspace:
    image: "angular/ngcontainer"
    ports:
      - "4200:4200"
      - "4201:4201"
      - "9876:9876"
    tty: true
    user: node
    working_dir: ${APP_CODE_PATH_CONTAINER}
    networks:
      - terrasse
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
